version: "3.9"

services:
  mongo82:
    image: mongo:8.2
    container_name: mongo82
    ports:
      - "27018:27017"
    volumes:
      - ./docker-volumes/mongo82:/data/db
    restart: unless-stopped
